In [1]:
import numpy as np

In [2]:
# Matrix multiplication
# Requirement: Inner dimension must match
# If we have a matrix A of size (2,3) and B of size (3,3)
# We can multiply AB (inner dimension is 3 and 3)
# We cannot multiply BA (inner dimension is 3 and 2)

In [3]:
# Refer https://www.wikihow.com/Multiply-Matrices

# More Matrix Operations

In [21]:
## Inverse of a matrix
## https://en.wikipedia.org/wiki/Inverse_(mathematics)
a = np.array([ [1,2], [3,4] ])
ainverse = np.linalg.inv(a)

In [8]:
ainverse

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [10]:
## Checking the inverse has been calculated correctly
ainverse.dot(a) # which gives us the identity matrix

array([[  1.00000000e+00,   0.00000000e+00],
       [  1.11022302e-16,   1.00000000e+00]])

In [11]:
# Calculating matrix determinent
np.linalg.det(a)

-2.0000000000000004

In [14]:
# Calculating the diagonal of a matrix
np.diag(a) # gives the value of elements in the diagonal

array([1, 4])

#### Sometimes we have a vector of numbers which represent the diagonal of the matrix and all the other elements are assumed to be zero


In [15]:
np.diag([1,2])

array([[1, 0],
       [0, 2]])

#### Sometimes we have two vectors and we have to do outer product. Refer https://en.wikipedia.org/wiki/Outer_product

In [16]:
# OUTER PRODUCT
a = np.array([1,2])
b = np.array([3,4])

In [17]:
np.outer(a,b)

array([[3, 4],
       [6, 8]])

In [18]:
# INNER PRODUCT
np.inner(a,b) # same as dot product

11

In [19]:
# Same thing for inner product as
np.dot(a,b)

11

#### Another common operation is MATRIX TRACE.

In [23]:
# It is the sum of the diagonals of the matrix.
a = np.array([ [1,2], [3,4] ])
np.diag(a).sum()

5

In [24]:
# Another method to find trace
np.trace(a)

5

In [30]:
### Eigen values and Eigen Vectors
x = np.random.randn(100, 3)
cov = np.cov(x)

In [31]:
cov.shape # wrong (100, 100) which is 

(100, 100)

In [32]:
# Take transpose of the matrix
cov = np.cov(x.T)

In [33]:
cov

array([[ 1.11926857,  0.07805127,  0.02184366],
       [ 0.07805127,  1.03140515,  0.06237471],
       [ 0.02184366,  0.06237471,  0.8602265 ]])

### Remember to transpose the data matrix before getting the co variance matrix

In [ ]:
#### Calculating the Eigen values and eigen vectors -- two ways
#### eigen_values, eigen_vectors = np.eig(C) OR
#### eigen_values, eigen_vectors = np.eigh(C)
#### where eig is for Symmetric matrix and eigh is only for Hermitian matrix only.
#### where symmetric matrix means a == a(transpose)
#### and hermitian matrix meand a == a(hermitian) which is conjugate transpose of a.
#### https://en.wikipedia.org/wiki/Symmetric_matrix
#### https://en.wikipedia.org/wiki/Hermitian_matrix