In [1]:
import numpy as np

In [2]:
#### Problem Statement: Ax = b
#### Solution: A(inverse)Ax = x = A(inverse)b

In [3]:
#### If the dimensionality of x is d we will have d unknowns.
#### THEOREM: AA(inverse) = Identity Matrix

In [4]:
a = np.array([ [1,2], [3,4] ])

In [5]:
a

array([[1, 2],
       [3, 4]])

In [8]:
b = np.array([1,2])

In [10]:
b

array([1, 2])

In [11]:
# SOlving for A(inverse)b
x = np.linalg.inv(a).dot(b)

In [12]:
x

array([ 0. ,  0.5])

In [14]:
# Another simple function provided by numpy is `solve`
x = np.linalg.solve(a,b)

In [15]:
x

array([ 0. ,  0.5])